JSpider Library: com.spider.jspiderlibrary2.Spider.Parser Class Reference
com.spider.jspiderlibrary2.Spider.Parser Class Reference
Public Member Functions
Parser (URL base)
void tagHandler (HTML.Tag tag)
void handleSimpleTag (HTML.Tag tag, MutableAttributeSet atributeSet, int pos)
void handleStartTag (HTML.Tag t, MutableAttributeSet a, int pos)
void handleText (char[] data, int pos)
Protected Member Functions
void handleLink (URL base, String str)
Protected Attributes
URL base
Detailed Description
Creo un parser de HTML en funcion de la clase HTML editor empleada para parsear y detectar los links
Definition at line 253 of file Spider.java.
Constructor & Destructor Documentation
com.spider.jspiderlibrary2.Spider.Parser.Parser (URL base)
Definition at line 261 of file Spider.java.
References com.spider.jspiderlibrary2.Spider.Parser.base.
Member Function Documentation
void com.spider.jspiderlibrary2.Spider.Parser.handleLink (URL base, String str) [protected]
Parameters:
base
str
Definition at line 397 of file Spider.java.
References com.spider.jspiderlibrary2.Spider.addURL(), com.spider.jspiderlibrary2.Spider.log(), com.spider.jspiderlibrary2.Spider.report, and com.spider.jspiderlibrary2.ISpiderReportable.spiderFoundURL().
Referenced by com.spider.jspiderlibrary2.Spider.Parser.handleSimpleTag().
void com.spider.jspiderlibrary2.Spider.Parser.handleSimpleTag (HTML.Tag tag, MutableAttributeSet atributeSet, int pos)
Definition at line 295 of file Spider.java.
References com.spider.jspiderlibrary2.Spider.Parser.base, com.spider.jspiderlibrary2.Spider.Parser.handleLink(), and com.spider.jspiderlibrary2.Spider.Parser.tagHandler().
Referenced by com.spider.jspiderlibrary2.Spider.Parser.handleStartTag().
void com.spider.jspiderlibrary2.Spider.Parser.handleStartTag (HTML.Tag t, MutableAttributeSet a, int pos)
Definition at line 357 of file Spider.java.
References com.spider.jspiderlibrary2.Spider.Parser.handleSimpleTag().
void com.spider.jspiderlibrary2.Spider.Parser.handleText (char[] data, int pos)
Parameters:
data gots the tag text
pos
Definition at line 368 of file Spider.java.
void com.spider.jspiderlibrary2.Spider.Parser.tagHandler (HTML.Tag tag)
Verifico si existen tags indeseados, es decir tags que no deben tener texto comparo el tag actual con el tag indeseado, con eso seteo el flag para notificarle al handleText que el tag NO debe ser procesado
Parameters:
tag a HTML.Tag
Definition at line 272 of file Spider.java.
Referenced by com.spider.jspiderlibrary2.Spider.Parser.handleSimpleTag().
Member Data Documentation
URL com.spider.jspiderlibrary2.Spider.Parser.base [protected]
Definition at line 257 of file Spider.java.
Referenced by com.spider.jspiderlibrary2.Spider.Parser.handleSimpleTag(), and com.spider.jspiderlibrary2.Spider.Parser.Parser().
The documentation for this class was generated from the following file:
src/main/java/com/spider/jspiderlibrary2/Spider.java