DLC Search Engine: com.utn.searchengine.PostList Class Reference
com.utn.searchengine.PostList Class Reference
Public Member Functions
Map< String, ArrayList
< WordTracker > > getPostList ()
void setPostList (Map< String, ArrayList< WordTracker >> postList)
PostList ()
PostList (Map< String, ArrayList< WordTracker >> postList)
void addDocumentWords (Map< String, Integer > words, String documentLocation)
int totalTimesThatWordRepeatsOnDocument (Word word, Document document)
int numberOfDocumentsWhereWordAppears (Word word)
Map< String, Word > getAllWords ()
Collection< Document > getCandidateDocuments (Collection< String > wordquery)
List< Word > getWordsDocument (Document document)
List< DocumentResults > getCandidateDocumentsFiltered (Collection< String > wordquery)
Detailed Description
An In-memory representation of a Post list. This is recommend to be on disc so probably soon, aPostListManager will difference this Local Post list form the other.
Author:
altamirano,peker,liberal
Definition at line 21 of file PostList.java.
Constructor & Destructor Documentation
com.utn.searchengine.PostList.PostList ()
Definition at line 33 of file PostList.java.
com.utn.searchengine.PostList.PostList (Map< String, ArrayList< WordTracker >> postList)
Definition at line 37 of file PostList.java.
Member Function Documentation
void com.utn.searchengine.PostList.addDocumentWords (Map< String, Integer > words, String documentLocation)
Adds the words of a document to the postList. In case a word already exists on the post list, it adds the newlocation where the word has been found, and the amount of times that it appeared.
Parameters:
words An array of locations and times that the word that the word has been found on that document.
documentLocation,: The document Location
Definition at line 50 of file PostList.java.
References dataaccess.dao.PostListDAO.Contains(), dataaccess.factories.DAOFactory.getActiveDAOFactory(), com.utn.searchengine.WordTracker.getFrequency(), dataaccess.factories.DAOFactory.getPostListDAO(), and dataaccess.dao.PostListDAO.grabarPostList().
Referenced by com.utn.searchengine.LocalWordCountManager.addDocument().
Map<String, Word> com.utn.searchengine.PostList.getAllWords ()
Returns:
A Single Map containing all the words that exist on the post list. This number should be the same that the number of words that exist on the vocabulary.
Definition at line 97 of file PostList.java.
References dataaccess.factories.DAOFactory.getActiveDAOFactory(), dataaccess.dao.WordDAO.getVocabulary(), and dataaccess.factories.DAOFactory.getWordDAO().
Collection<Document> com.utn.searchengine.PostList.getCandidateDocuments (Collection< String > wordquery)
Collecion de documentos candidatos
Parameters:
wordquery palabras de la query
Returns:
collecion de documentos que aparece las palabras de la query
Definition at line 107 of file PostList.java.
References dataaccess.factories.DAOFactory.getActiveDAOFactory(), dataaccess.factories.DAOFactory.getPostListDAO(), and dataaccess.dao.PostListDAO.obtenerDocumentoCandidatos().
List<DocumentResults> com.utn.searchengine.PostList.getCandidateDocumentsFiltered (Collection< String > wordquery)
devuelve los documentos candidatos filtrados por la frecuencia y el nr
Parameters:
wordquery palabras de la query
Returns:
una lista de documentos candidatos filtrado
Definition at line 125 of file PostList.java.
References dataaccess.factories.DAOFactory.getActiveDAOFactory(), dataaccess.dao.PostListDAO.getFilteredCandidates(), and dataaccess.factories.DAOFactory.getPostListDAO().
Referenced by com.utn.searchengine.LocalWordCountManager.determinateBestSimilitude().
Map<String, ArrayList<WordTracker> > com.utn.searchengine.PostList.getPostList ()
Definition at line 25 of file PostList.java.
List<Word> com.utn.searchengine.PostList.getWordsDocument (Document document)
las palabras de un documentos
Parameters:
document que quiero que me traiga palabras
Returns:
la lista de palabras
Definition at line 116 of file PostList.java.
References dataaccess.factories.DAOFactory.getActiveDAOFactory(), dataaccess.factories.DAOFactory.getPostListDAO(), and dataaccess.dao.PostListDAO.getWordsDocument().
Referenced by com.utn.searchengine.LocalWordCountManager.getDocumentModule().
int com.utn.searchengine.PostList.numberOfDocumentsWhereWordAppears (Word word)
cantidad de documento que aparece una palabra
Parameters:
word,: A Word
Returns:
The number of documents where the word has been found at least once.
Definition at line 86 of file PostList.java.
References dataaccess.factories.DAOFactory.getActiveDAOFactory(), dataaccess.dao.WordDAO.getNrWord(), and dataaccess.factories.DAOFactory.getWordDAO().
Referenced by com.utn.searchengine.LocalWordCountManager.numberOfDocumentsWhereWordAppears().
void com.utn.searchengine.PostList.setPostList (Map< String, ArrayList< WordTracker >> postList)
Definition at line 29 of file PostList.java.
int com.utn.searchengine.PostList.totalTimesThatWordRepeatsOnDocument (Word word, Document document)
Frecuencia de una palabra en un documento
Parameters:
word,: A Word
document,: A Document
Returns:
The total times that the word appears on the document.
Definition at line 76 of file PostList.java.
References dataaccess.factories.DAOFactory.getActiveDAOFactory(), dataaccess.factories.DAOFactory.getPostListDAO(), and dataaccess.dao.PostListDAO.getTF().
Referenced by com.utn.searchengine.LocalWordCountManager.timesThatAWordRepeatsOnDocument().
The documentation for this class was generated from the following file:
src/main/java/com/utn/searchengine/PostList.java