DLC Search Engine: dataaccess.postgresql.PostgreSQLPostListDAO Class Reference
dataaccess.postgresql.PostgreSQLPostListDAO Class Reference
Public Member Functions
ArrayList< Document > obtenerDocumentoCandidatos (Collection< String > c)
int getNrWord (Word word)
int getTF (Word word, Document document)
boolean grabarPostList (Word word, Document document, int fr)
boolean Contains (String palabra)
ArrayList< Word > getWordsDocument (Document document)
List< DocumentResults > getFilteredCandidates (Collection< String > c)
Detailed Description
Author:
Altamirano Peker Liberal
Definition at line 23 of file PostgreSQLPostListDAO.java.
Member Function Documentation
boolean dataaccess.postgresql.PostgreSQLPostListDAO.Contains (String palabra)
Parameters:
palabra,: Una cadena que representa el texto de una palabra
Returns:
: true si esa cadena esta asociada a una lista de posteo.
Implements dataaccess.dao.PostListDAO.
Definition at line 156 of file PostgreSQLPostListDAO.java.
References dataaccess.dbmanager.PostgreDBManager.getConnection().
List<DocumentResults> dataaccess.postgresql.PostgreSQLPostListDAO.getFilteredCandidates (Collection< String > c)
Los documentos recuperados que se traian como candidatos eran demasiados y muchos no resultaban muy significativos, por lo que se creo este metodo para recuperar una cantidad mas precisa de documentos candidatos
Parameters:
c,: Una coleccion de terminos
Returns:
Los documentos candidatos filtrados.
Implements dataaccess.dao.PostListDAO.
Definition at line 202 of file PostgreSQLPostListDAO.java.
References dataaccess.dbmanager.PostgreDBManager.getConnection(), com.utn.searchengine.Word.getName(), and com.utn.searchengine.DocumentResults.setNumberOfQueryWords().
int dataaccess.postgresql.PostgreSQLPostListDAO.getNrWord (Word word)
Definition at line 71 of file PostgreSQLPostListDAO.java.
References dataaccess.dbmanager.PostgreDBManager.getConnection(), and com.utn.searchengine.Word.getName().
int dataaccess.postgresql.PostgreSQLPostListDAO.getTF (Word word, Document document)
Parameters:
word,: una Palabra
document,: un Documento
Returns:
La cantidad de veces que una palabra aparece en un documento paricular
Implements dataaccess.dao.PostListDAO.
Definition at line 100 of file PostgreSQLPostListDAO.java.
References dataaccess.dbmanager.PostgreDBManager.getConnection(), com.utn.searchengine.Document.getLocation(), and com.utn.searchengine.Word.getName().
ArrayList<Word> dataaccess.postgresql.PostgreSQLPostListDAO.getWordsDocument (Document document)
Parameters:
document,: Un Documento
Returns:
Una lista de palabras que pertenecen al documento seleccionado
Implements dataaccess.dao.PostListDAO.
Definition at line 178 of file PostgreSQLPostListDAO.java.
References dataaccess.dbmanager.PostgreDBManager.getConnection(), and com.utn.searchengine.Document.getLocation().
boolean dataaccess.postgresql.PostgreSQLPostListDAO.grabarPostList (Word word, Document document, int fr)
Graba los elementosde la lista de posteo
Parameters:
word,: Una Palabra
document,: Un Documento
fr,: La frecuencia de la palabra en el documento.
Returns:
true si se pudo grabar bien, false si el elemento ya existe y se actualizo.
Implements dataaccess.dao.PostListDAO.
Definition at line 132 of file PostgreSQLPostListDAO.java.
References dataaccess.dbmanager.PostgreDBManager.getConnection(), com.utn.searchengine.Document.getLocation(), and com.utn.searchengine.Word.getName().
ArrayList<Document> dataaccess.postgresql.PostgreSQLPostListDAO.obtenerDocumentoCandidatos (Collection< String > c)
Parameters:
c
Returns:
Una lista de documentos candidatos
Implements dataaccess.dao.PostListDAO.
Definition at line 29 of file PostgreSQLPostListDAO.java.
References dataaccess.dbmanager.PostgreDBManager.getConnection(), and com.utn.searchengine.Word.getName().
The documentation for this class was generated from the following file:
src/main/java/DataAccess/postgresql/PostgreSQLPostListDAO.java