DLC Search Engine: dataaccess.postgresql.PostgreSQLWordDAO Class Reference
dataaccess.postgresql.PostgreSQLWordDAO Class Reference
Public Member Functions
boolean saveWord (Word word)
Word getWord (Word palabra)
Map< String, Word > getVocabulary ()
boolean deleteWord (Word palabra)
int getNrWord (Word word)
Detailed Description
Author:
Altamirano Peker Liberal
Definition at line 17 of file PostgreSQLWordDAO.java.
Member Function Documentation
boolean dataaccess.postgresql.PostgreSQLWordDAO.deleteWord (Word word)
Elimina la Word de la base de datos
Parameters:
word la palabra a eliminar
Returns:
true si el word se pudo eliminar exitosamente, false en caso contrario
Implements dataaccess.dao.WordDAO.
Definition at line 99 of file PostgreSQLWordDAO.java.
References dataaccess.dbmanager.PostgreDBManager.getConnection(), and com.utn.searchengine.Word.getName().
int dataaccess.postgresql.PostgreSQLWordDAO.getNrWord (Word word)
Implements dataaccess.dao.WordDAO.
Definition at line 120 of file PostgreSQLWordDAO.java.
References dataaccess.dbmanager.PostgreDBManager.getConnection(), and com.utn.searchengine.Word.getName().
Map<String, Word> dataaccess.postgresql.PostgreSQLWordDAO.getVocabulary ()
Obtiene el identificador del word en la base de datos
Parameters:
word el Word de la cual se desea saber su ID
Returns:
el id del word
Implements dataaccess.dao.WordDAO.
Definition at line 77 of file PostgreSQLWordDAO.java.
References dataaccess.dbmanager.PostgreDBManager.getConnection().
Word dataaccess.postgresql.PostgreSQLWordDAO.getWord (Word palabra)
Obtiene la word de la base de datos en base al objeto de búsqueda pasado por parámetro.
Parameters:
word Word a buscar
Returns:
la word almacenada en la base de datos, null si la misma no existia o existen problemas de acceso a la base.
Implements dataaccess.dao.WordDAO.
Definition at line 55 of file PostgreSQLWordDAO.java.
References dataaccess.dbmanager.PostgreDBManager.getConnection(), and com.utn.searchengine.Word.getName().
boolean dataaccess.postgresql.PostgreSQLWordDAO.saveWord (Word word)
Graba un Word en la base de datos. Si la misma ya existia la actualiza y sino la inserta.
Parameters:
word Word que se desea grabar
Returns:
true si se pudo realizar exitosamente la operación, false en caso contrario.
Implements dataaccess.dao.WordDAO.
Definition at line 26 of file PostgreSQLWordDAO.java.
References dataaccess.dbmanager.PostgreDBManager.getConnection(), com.utn.searchengine.Word.getMaxTF(), com.utn.searchengine.Word.getName(), and com.utn.searchengine.Word.getNr().
The documentation for this class was generated from the following file:
src/main/java/DataAccess/postgresql/PostgreSQLWordDAO.java