DLC Search Engine: com.utn.searchengine.WordCount Class Reference
com.utn.searchengine.WordCount Class Reference
Static Public Member Functions
static Map< String, Integer > retrieveWordCount (Document doc)
static int getTF (Word word, Document document)
Detailed Description
This class provides the utility of detect the different words that exist on a document
Author:
altamirano,peker,liberal
Definition at line 17 of file WordCount.java.
Member Function Documentation
static int com.utn.searchengine.WordCount.getTF (Word word, Document document) [static]
Calcula cuantas veces aparece la palabra en un documento
Parameters:
word
document
Returns:
el tf de la word
Definition at line 86 of file WordCount.java.
References com.utn.searchengine.Word.getName(), and com.utn.searchengine.Document.getText().
Referenced by com.utn.searchengine.LocalWordCountManager.estimateWeight().
static Map<String, Integer> com.utn.searchengine.WordCount.retrieveWordCount (Document doc) [static]
Parameters:
filePath,: A path to a disk file
Returns:
a collection of words and the times that those words repeats on the file
Definition at line 24 of file WordCount.java.
References com.utn.searchengine.Document.getText(), com.utn.searchengine.StopWordMap.isStopWord(), com.utn.searchengine.StopWordMap.readStopWordList(), and com.utn.searchengine.StopWordMap.stopWordIdiomDocumentFinder().
Referenced by com.utn.searchengine.LocalWordCountManager.addDocument(), and com.utn.searchengine.LocalWordCountManager.determinateBestSimilitude().
The documentation for this class was generated from the following file:
src/main/java/com/utn/searchengine/WordCount.java