DLC Search Engine: com.utn.searchengine.Vocabulary Class Reference
com.utn.searchengine.Vocabulary Class Reference
Public Member Functions
Map< String, Word > getVocabularyWords ()
void setVocabularyWords (Map< String, Word > vocabularyWords)
void loadVocabularyWords ()
Vocabulary ()
Vocabulary (Map< String, Word > vocabularyWords)
void addWord (Word entry)
void addDocumentWords (Map< String, Integer > words)
boolean containsWord (String word)
String toString ()
Detailed Description
This class is a temporal-in memory array that manages the information about the words
Author:
altamirano,peker,liberal
Definition at line 17 of file Vocabulary.java.
Constructor & Destructor Documentation
com.utn.searchengine.Vocabulary.Vocabulary ()
Definition at line 33 of file Vocabulary.java.
com.utn.searchengine.Vocabulary.Vocabulary (Map< String, Word > vocabularyWords)
Definition at line 37 of file Vocabulary.java.
Member Function Documentation
void com.utn.searchengine.Vocabulary.addDocumentWords (Map< String, Integer > words)
adds all the new words of a new document to the vocabulary
Parameters:
words,: a collection of words
Definition at line 54 of file Vocabulary.java.
References dataaccess.factories.DAOFactory.getActiveDAOFactory(), com.utn.searchengine.Word.getMaxTF(), com.utn.searchengine.Word.getName(), com.utn.searchengine.Word.getNr(), dataaccess.factories.DAOFactory.getWordDAO(), dataaccess.dao.WordDAO.saveWord(), com.utn.searchengine.Word.setMaxTF(), and com.utn.searchengine.Word.setNr().
Referenced by com.utn.searchengine.LocalWordCountManager.addDocument().
void com.utn.searchengine.Vocabulary.addWord (Word entry)
Adds aword to the map
Parameters:
word
Returns:
Definition at line 46 of file Vocabulary.java.
References com.utn.searchengine.Word.getName().
boolean com.utn.searchengine.Vocabulary.containsWord (String word)
Parameters:
word a word
Returns:
true if word is containes
Definition at line 87 of file Vocabulary.java.
Referenced by com.utn.searchengine.LocalWordCountManager.filterQuery().
Map<String, Word> com.utn.searchengine.Vocabulary.getVocabularyWords ()
Definition at line 19 of file Vocabulary.java.
Referenced by com.utn.searchengine.LocalWordCountManager.determinateSimilitude(), and com.utn.searchengine.LocalWordCountManager.getQueryModule().
void com.utn.searchengine.Vocabulary.loadVocabularyWords ()
Definition at line 27 of file Vocabulary.java.
References dataaccess.factories.DAOFactory.getActiveDAOFactory(), dataaccess.dao.WordDAO.getVocabulary(), and dataaccess.factories.DAOFactory.getWordDAO().
Referenced by com.utn.searchengine.LocalWordCountManager.LocalWordCountManager().
void com.utn.searchengine.Vocabulary.setVocabularyWords (Map< String, Word > vocabularyWords)
Definition at line 23 of file Vocabulary.java.
String com.utn.searchengine.Vocabulary.toString ()
Definition at line 92 of file Vocabulary.java.
The documentation for this class was generated from the following file:
src/main/java/com/utn/searchengine/Vocabulary.java