DLC Search Engine: com.utn.searchengine.LocalWordCountManager Class Reference
com.utn.searchengine.LocalWordCountManager Class Reference
Classes
class Compare
Public Member Functions
LocalWordCountManager ()
void addDocument (Document document)
int getTotalNumberOfDocuments ()
int timesThatAWordRepeatsOnDocument (Word word, Document document)
int numberOfDocumentsWhereWordAppears (Word word)
double inverseFrecuency (Word word)
double getDocumentModule (Document document, double invFrecuency)
double estimateWeight (Word word, Document document)
Collection< Similitude > determinateBestSimilitude (Document document)
double getQueryModule (Map< String, Integer > wordsOfQuery)
Similitude determinateSimilitude (Map< String, Integer > wordsOfQuery, Document document1, Document document2)
Map< String, Integer > filterQuery (Map< String, Integer > wordsOfQuery)
Detailed Description
An implementation of services that are usefull to count words This are using local Structures and can dissapear once the structure is migrated to database, but the interface probably will be the same.
Author:
altamirano,peker,liberal
Definition at line 22 of file LocalWordCountManager.java.
Constructor & Destructor Documentation
com.utn.searchengine.LocalWordCountManager.LocalWordCountManager ()
Definition at line 29 of file LocalWordCountManager.java.
References com.utn.searchengine.Vocabulary.loadVocabularyWords().
Member Function Documentation
void com.utn.searchengine.LocalWordCountManager.addDocument (Document document)
Adds a document to all the structures.
Parameters:
document a Document
Definition at line 41 of file LocalWordCountManager.java.
References com.utn.searchengine.DocumentManager.addDocument(), com.utn.searchengine.PostList.addDocumentWords(), com.utn.searchengine.Vocabulary.addDocumentWords(), com.utn.searchengine.Document.getLocation(), and com.utn.searchengine.WordCount.retrieveWordCount().
Collection<Similitude> com.utn.searchengine.LocalWordCountManager.determinateBestSimilitude (Document document)
A query can have different similitudes between documents. Here the list of similitudes between a query and all the documents
Parameters:
document the query
Returns:
An Array of Similitude.
Definition at line 168 of file LocalWordCountManager.java.
References com.utn.searchengine.LocalWordCountManager.determinateSimilitude(), com.utn.searchengine.LocalWordCountManager.filterQuery(), com.utn.searchengine.PostList.getCandidateDocumentsFiltered(), com.utn.searchengine.LocalWordCountManager.getQueryModule(), com.utn.searchengine.WordCount.retrieveWordCount(), and com.utn.searchengine.Document.setModule().
Similitude com.utn.searchengine.LocalWordCountManager.determinateSimilitude (Map< String, Integer > wordsOfQuery, Document document1, Document document2)
Determina la similitud entre dos documentos
Parameters:
wordsOfQuery las palabra que aparecen en la query
document1 documento de la base de datos
document2 documento de la query
Returns:
el coseno(similitud entre dos documentos)
Definition at line 245 of file LocalWordCountManager.java.
References com.utn.searchengine.LocalWordCountManager.estimateWeight(), com.utn.searchengine.Word.getName(), and com.utn.searchengine.Vocabulary.getVocabularyWords().
Referenced by com.utn.searchengine.LocalWordCountManager.determinateBestSimilitude().
double com.utn.searchengine.LocalWordCountManager.estimateWeight (Word word, Document document)
The Weight of a word is important to determinate wich words are more usefull to perform a search and wich of them not. Each word can have different weight on different documents.
Parameters:
word,: A Word
document,: A Document.
Returns:
The weight of the word on the Document.
Definition at line 131 of file LocalWordCountManager.java.
References com.utn.searchengine.LocalWordCountManager.getDocumentModule(), com.utn.searchengine.Document.getLocation(), com.utn.searchengine.Document.getModule(), com.utn.searchengine.WordCount.getTF(), com.utn.searchengine.LocalWordCountManager.inverseFrecuency(), com.utn.searchengine.DocumentManager.setDocumentModule(), com.utn.searchengine.Document.setModule(), and com.utn.searchengine.LocalWordCountManager.timesThatAWordRepeatsOnDocument().
Referenced by com.utn.searchengine.LocalWordCountManager.determinateSimilitude().
Map<String, Integer> com.utn.searchengine.LocalWordCountManager.filterQuery (Map< String, Integer > wordsOfQuery)
filtras sacas de la query las palabra que no esta en ningun documento
Parameters:
wordsOfQuery Map de palabras de la query
Returns:
devuelve el Map de la query
Definition at line 271 of file LocalWordCountManager.java.
References com.utn.searchengine.Vocabulary.containsWord().
Referenced by com.utn.searchengine.LocalWordCountManager.determinateBestSimilitude().
double com.utn.searchengine.LocalWordCountManager.getDocumentModule (Document document, double invFrecuency)
Each Document gots a module that can be considered as a position Vector. The module of a document will depend of the total amount of words, so, if new words are added to the vocabulary, all the document modules will have to be recalculated.
Parameters:
document,: A document
Returns:
The module that represents de vector of the document.
Definition at line 104 of file LocalWordCountManager.java.
References com.utn.searchengine.PostList.getWordsDocument().
Referenced by com.utn.searchengine.LocalWordCountManager.estimateWeight().
double com.utn.searchengine.LocalWordCountManager.getQueryModule (Map< String, Integer > wordsOfQuery)
The words of a query need to be taken as a document, and the document needs to have a module. Because htis module is temporal and wount be saved on the postList, a different method was needed to calculate it.
Parameters:
query
Returns:
The module of the query
Definition at line 222 of file LocalWordCountManager.java.
References com.utn.searchengine.Vocabulary.getVocabularyWords(), and com.utn.searchengine.LocalWordCountManager.inverseFrecuency().
Referenced by com.utn.searchengine.LocalWordCountManager.determinateBestSimilitude().
int com.utn.searchengine.LocalWordCountManager.getTotalNumberOfDocuments ()
Returns:
the total of documents that exist.
Definition at line 52 of file LocalWordCountManager.java.
References com.utn.searchengine.DocumentManager.documentsSize().
Referenced by com.utn.searchengine.LocalWordCountManager.inverseFrecuency().
double com.utn.searchengine.LocalWordCountManager.inverseFrecuency (Word word)
The inverse frecuency is a common operation on the Weigth calcule.
Parameters:
word,: A Word
Returns:
The Base 10 Logaritm of the difference between the total documents and the number of documents where the word appears.
Definition at line 81 of file LocalWordCountManager.java.
References com.utn.searchengine.Word.getNr(), and com.utn.searchengine.LocalWordCountManager.getTotalNumberOfDocuments().
Referenced by com.utn.searchengine.LocalWordCountManager.estimateWeight(), and com.utn.searchengine.LocalWordCountManager.getQueryModule().
int com.utn.searchengine.LocalWordCountManager.numberOfDocumentsWhereWordAppears (Word word)
Parameters:
word,: A Word
Returns:
The number of documents that contain the Word at least once
Definition at line 71 of file LocalWordCountManager.java.
References com.utn.searchengine.PostList.numberOfDocumentsWhereWordAppears().
int com.utn.searchengine.LocalWordCountManager.timesThatAWordRepeatsOnDocument (Word word, Document document)
Parameters:
word,: A Word
document,: A Document
Returns:
the times that the document contains the word.
Definition at line 62 of file LocalWordCountManager.java.
References com.utn.searchengine.PostList.totalTimesThatWordRepeatsOnDocument().
Referenced by com.utn.searchengine.LocalWordCountManager.estimateWeight().
The documentation for this class was generated from the following file:
src/main/java/com/utn/searchengine/LocalWordCountManager.java