DLC Search Engine: dataaccess.dbmanager.PostgreDBManager Class Reference
dataaccess.dbmanager.PostgreDBManager Class Reference
Static Public Member Functions
static synchronized Connection getConnection ()
Detailed Description
Clase que tiene el driver sql para la coneccion a Postgres
Author:
Altamirado Liberal Peker
Definition at line 11 of file PostgreDBManager.java.
Member Function Documentation
static synchronized Connection dataaccess.dbmanager.PostgreDBManager.getConnection () [static]
Returns:
la única instancia válida de DBManager
Definition at line 37 of file PostgreDBManager.java.
Referenced by dataaccess.postgresql.PostgreSQLPostListDAO.Contains(), dataaccess.postgresql.PostgreSQLWordDAO.deleteWord(), dataaccess.postgresql.PostgreSQLPostListDAO.getFilteredCandidates(), dataaccess.postgresql.PostgreSQLPostListDAO.getNrWord(), dataaccess.postgresql.PostgreSQLWordDAO.getNrWord(), dataaccess.postgresql.PostgreSQLPostListDAO.getTF(), dataaccess.postgresql.PostgreSQLWordDAO.getVocabulary(), dataaccess.postgresql.PostgreSQLWordDAO.getWord(), dataaccess.postgresql.PostgreSQLPostListDAO.getWordsDocument(), dataaccess.postgresql.PostgreSQLPostListDAO.grabarPostList(), dataaccess.postgresql.PostgreSQLDocumentDAO.grabarWebSite(), dataaccess.postgresql.PostgreSQLDocumentDAO.obtenerCantidadDocument(), dataaccess.postgresql.PostgreSQLDocumentDAO.obtenerDocument(), dataaccess.postgresql.PostgreSQLPostListDAO.obtenerDocumentoCandidatos(), and dataaccess.postgresql.PostgreSQLWordDAO.saveWord().
The documentation for this class was generated from the following file:
src/main/java/DataAccess/dbmanager/PostgreDBManager.java