DLC Search Engine: dataaccess.factories.DAOFactory Class Reference
dataaccess.factories.DAOFactory Class Reference
Public Member Functions
abstract WordDAO getWordDAO ()
abstract DocumentDAO getDocumentDAO ()
abstract PostListDAO getPostListDAO ()
Static Public Member Functions
static DAOFactory getDAOFactory (int factory)
static DAOFactory getActiveDAOFactory ()
Static Public Attributes
static final int POSTGRE = 1
static final int activeFactoryPostgre = POSTGRE
Detailed Description
Clase abstracta que representa una fábrica de DAOs.
Author:
Altamirano Liberal Peker
Definition at line 13 of file DAOFactory.java.
Member Function Documentation
static DAOFactory dataaccess.factories.DAOFactory.getActiveDAOFactory () [static]
Devuelve la factory activa
Returns:
la factory activa (según el tipo de persistencia a utilizar)
Definition at line 40 of file DAOFactory.java.
References dataaccess.factories.DAOFactory.activeFactoryPostgre, and dataaccess.factories.DAOFactory.getDAOFactory().
Referenced by com.utn.searchengine.DocumentManager.addDocument(), com.utn.searchengine.PostList.addDocumentWords(), com.utn.searchengine.Vocabulary.addDocumentWords(), com.utn.searchengine.DocumentManager.DocumentManager(), com.utn.searchengine.PostList.getAllWords(), com.utn.searchengine.PostList.getCandidateDocuments(), com.utn.searchengine.PostList.getCandidateDocumentsFiltered(), com.utn.searchengine.DocumentManager.getDocumentModule(), com.utn.searchengine.PostList.getWordsDocument(), com.utn.searchengine.Vocabulary.loadVocabularyWords(), com.utn.searchengine.PostList.numberOfDocumentsWhereWordAppears(), com.utn.searchengine.DocumentManager.setDocumentModule(), and com.utn.searchengine.PostList.totalTimesThatWordRepeatsOnDocument().
static DAOFactory dataaccess.factories.DAOFactory.getDAOFactory (int factory) [static]
Definition at line 26 of file DAOFactory.java.
References dataaccess.factories.DAOFactory.POSTGRE.
Referenced by dataaccess.factories.DAOFactory.getActiveDAOFactory().
abstract DocumentDAO dataaccess.factories.DAOFactory.getDocumentDAO () [pure virtual]
Implemented in dataaccess.factories.PostgreSQLDAOFactory.
Referenced by com.utn.searchengine.DocumentManager.addDocument(), com.utn.searchengine.DocumentManager.DocumentManager(), com.utn.searchengine.DocumentManager.getDocumentModule(), and com.utn.searchengine.DocumentManager.setDocumentModule().
abstract PostListDAO dataaccess.factories.DAOFactory.getPostListDAO () [pure virtual]
Implemented in dataaccess.factories.PostgreSQLDAOFactory.
Referenced by com.utn.searchengine.PostList.addDocumentWords(), com.utn.searchengine.PostList.getCandidateDocuments(), com.utn.searchengine.PostList.getCandidateDocumentsFiltered(), com.utn.searchengine.PostList.getWordsDocument(), and com.utn.searchengine.PostList.totalTimesThatWordRepeatsOnDocument().
abstract WordDAO dataaccess.factories.DAOFactory.getWordDAO () [pure virtual]
Implemented in dataaccess.factories.PostgreSQLDAOFactory.
Referenced by com.utn.searchengine.Vocabulary.addDocumentWords(), com.utn.searchengine.PostList.getAllWords(), com.utn.searchengine.Vocabulary.loadVocabularyWords(), and com.utn.searchengine.PostList.numberOfDocumentsWhereWordAppears().
Member Data Documentation
final int dataaccess.factories.DAOFactory.activeFactoryPostgre = POSTGRE [static]
Definition at line 18 of file DAOFactory.java.
Referenced by dataaccess.factories.DAOFactory.getActiveDAOFactory().
final int dataaccess.factories.DAOFactory.POSTGRE = 1 [static]
Definition at line 16 of file DAOFactory.java.
Referenced by dataaccess.factories.DAOFactory.getDAOFactory().
The documentation for this class was generated from the following file:
src/main/java/DataAccess/factories/DAOFactory.java