DLC Search Engine: com.utn.searchengine.DocumentManager Class Reference
com.utn.searchengine.DocumentManager Class Reference
Public Member Functions
double getDocumentModule (Document document)
boolean setDocumentModule (Document document)
void addDocument (Document document)
int documentsSize ()
DocumentManager ()
String toString ()
Detailed Description
This class is an auxiliar to manage all the basic info about the documents.
Author:
altamirano,peker,liberal
Definition at line 13 of file DocumentManager.java.
Constructor & Destructor Documentation
com.utn.searchengine.DocumentManager.DocumentManager ()
Recupera de la base de datos la cantidad de documentos
Definition at line 53 of file DocumentManager.java.
References dataaccess.factories.DAOFactory.getActiveDAOFactory(), dataaccess.factories.DAOFactory.getDocumentDAO(), and dataaccess.dao.DocumentDAO.obtenerCantidadDocument().
Member Function Documentation
void com.utn.searchengine.DocumentManager.addDocument (Document document)
Agrega un documento a la base de datos
Parameters:
document
Definition at line 36 of file DocumentManager.java.
References dataaccess.factories.DAOFactory.getActiveDAOFactory(), dataaccess.factories.DAOFactory.getDocumentDAO(), and dataaccess.dao.DocumentDAO.grabarWebSite().
Referenced by com.utn.searchengine.LocalWordCountManager.addDocument().
int com.utn.searchengine.DocumentManager.documentsSize ()
devuelve la cantidad de documento de la base de datos
Returns:
el size que es la cantidad de documentos
Definition at line 46 of file DocumentManager.java.
Referenced by com.utn.searchengine.LocalWordCountManager.getTotalNumberOfDocuments().
double com.utn.searchengine.DocumentManager.getDocumentModule (Document document)
Recupera el modulo de un documento de la base de datos
Parameters:
document A document
Returns:
the module of the documen. If the document is not present on the documentManager or its module hasn't been set, it returns -1
Definition at line 23 of file DocumentManager.java.
References dataaccess.factories.DAOFactory.getActiveDAOFactory(), dataaccess.factories.DAOFactory.getDocumentDAO(), com.utn.searchengine.Document.getModule(), and dataaccess.dao.DocumentDAO.obtenerDocument().
boolean com.utn.searchengine.DocumentManager.setDocumentModule (Document document)
Definition at line 28 of file DocumentManager.java.
References dataaccess.factories.DAOFactory.getActiveDAOFactory(), dataaccess.factories.DAOFactory.getDocumentDAO(), and dataaccess.dao.DocumentDAO.grabarWebSite().
Referenced by com.utn.searchengine.LocalWordCountManager.estimateWeight().
String com.utn.searchengine.DocumentManager.toString ()
Definition at line 58 of file DocumentManager.java.
The documentation for this class was generated from the following file:
src/main/java/com/utn/searchengine/DocumentManager.java