DLC Search Engine: dataaccess.dao.PostListDAO Interface Reference
dataaccess.dao.PostListDAO Interface Reference
Public Member Functions
List< Document > obtenerDocumentoCandidatos (Collection< String > c)
int getTF (Word word, Document document)
boolean grabarPostList (Word word, Document document, int fr)
boolean Contains (String palabra)
List< Word > getWordsDocument (Document document)
List< DocumentResults > getFilteredCandidates (Collection< String > c)
Detailed Description
Esta interface define las operaciones validas a realizarse en términos de persistencia sobre un objeto de tipo PostList.
Author:
Altamirado Liberal Peker
Definition at line 15 of file PostListDAO.java.
Member Function Documentation
boolean dataaccess.dao.PostListDAO.Contains (String palabra)
Parameters:
palabra,: Una cadena que representa el texto de una palabra
Returns:
: true si esa cadena esta asociada a una lista de posteo.
Implemented in dataaccess.postgresql.PostgreSQLPostListDAO.
Referenced by com.utn.searchengine.PostList.addDocumentWords().
List<DocumentResults> dataaccess.dao.PostListDAO.getFilteredCandidates (Collection< String > c)
Los documentos recuperados que se traian como candidatos eran demasiados y muchos no resultaban muy significativos, por lo que se creo este metodo para recuperar una cantidad mas precisa de documentos candidatos
Parameters:
c,: Una coleccion de terminos
Returns:
Los documentos candidatos filtrados.
Implemented in dataaccess.postgresql.PostgreSQLPostListDAO.
Referenced by com.utn.searchengine.PostList.getCandidateDocumentsFiltered().
int dataaccess.dao.PostListDAO.getTF (Word word, Document document)
Parameters:
word,: una Palabra
document,: un Documento
Returns:
La cantidad de veces que una palabra aparece en un documento paricular
Implemented in dataaccess.postgresql.PostgreSQLPostListDAO.
Referenced by com.utn.searchengine.PostList.totalTimesThatWordRepeatsOnDocument().
List<Word> dataaccess.dao.PostListDAO.getWordsDocument (Document document)
Parameters:
document,: Un Documento
Returns:
Una lista de palabras que pertenecen al documento seleccionado
Implemented in dataaccess.postgresql.PostgreSQLPostListDAO.
Referenced by com.utn.searchengine.PostList.getWordsDocument().
boolean dataaccess.dao.PostListDAO.grabarPostList (Word word, Document document, int fr)
Graba los elementosde la lista de posteo
Parameters:
word,: Una Palabra
document,: Un Documento
fr,: La frecuencia de la palabra en el documento.
Returns:
true si se pudo grabar bien, false si el elemento ya existe y se actualizo.
Implemented in dataaccess.postgresql.PostgreSQLPostListDAO.
Referenced by com.utn.searchengine.PostList.addDocumentWords().
List<Document> dataaccess.dao.PostListDAO.obtenerDocumentoCandidatos (Collection< String > c)
Parameters:
c
Returns:
Una lista de documentos candidatos
Implemented in dataaccess.postgresql.PostgreSQLPostListDAO.
Referenced by com.utn.searchengine.PostList.getCandidateDocuments().
The documentation for this interface was generated from the following file:
src/main/java/DataAccess/dao/PostListDAO.java