DLC Search Engine: dataaccess.dao.WordDAO Interface Reference
dataaccess.dao.WordDAO Interface Reference
Public Member Functions
boolean saveWord (Word word)
boolean deleteWord (Word word)
Word getWord (Word word)
Map< String, Word > getVocabulary ()
int getNrWord (Word word)
Detailed Description
Esta interface define las operaciones validas a realizarse en términos de persistencia sobre un objeto de tipo Word.
Author:
Altamirano Liberal Peker
Definition at line 13 of file WordDAO.java.
Member Function Documentation
boolean dataaccess.dao.WordDAO.deleteWord (Word word)
Elimina la Word de la base de datos
Parameters:
word la palabra a eliminar
Returns:
true si el word se pudo eliminar exitosamente, false en caso contrario
Implemented in dataaccess.postgresql.PostgreSQLWordDAO.
int dataaccess.dao.WordDAO.getNrWord (Word word)
Implemented in dataaccess.postgresql.PostgreSQLWordDAO.
Referenced by com.utn.searchengine.PostList.numberOfDocumentsWhereWordAppears().
Map<String, Word> dataaccess.dao.WordDAO.getVocabulary ()
Obtiene el identificador del word en la base de datos
Parameters:
word el Word de la cual se desea saber su ID
Returns:
el id del word
Implemented in dataaccess.postgresql.PostgreSQLWordDAO.
Referenced by com.utn.searchengine.PostList.getAllWords(), and com.utn.searchengine.Vocabulary.loadVocabularyWords().
Word dataaccess.dao.WordDAO.getWord (Word word)
Obtiene la Word correspondiente de la base de datos.
Parameters:
word la palabra a obtener
Returns:
el word que se desea obtener, null en caso que la palabra no exista
Implemented in dataaccess.postgresql.PostgreSQLWordDAO.
boolean dataaccess.dao.WordDAO.saveWord (Word word)
Graba un Word en la base de datos. Si el Word ya existia la actualiza y si no existia la inserta en la base de datos.
Parameters:
word la palabra a grabar
Returns:
true si la operacion se pudo realizar exitosamente, false en caso contrario
Implemented in dataaccess.postgresql.PostgreSQLWordDAO.
Referenced by com.utn.searchengine.Vocabulary.addDocumentWords().
The documentation for this interface was generated from the following file:
src/main/java/DataAccess/dao/WordDAO.java