DLC Search Engine: com.utn.searchengine.DocumentResults Class Reference
com.utn.searchengine.DocumentResults Class Reference
Public Member Functions
Document getDocument ()
void setDocument (Document document)
int getNumberOfQueryWords ()
void setNumberOfQueryWords (int numberOfQueryWords)
boolean equals (Object obj)
int hashCode ()
DocumentResults (Document document, int numberOfQueryWords)
Detailed Description
Author:
Altamirano,Liberal,Peker
Definition at line 11 of file DocumentResults.java.
Constructor & Destructor Documentation
com.utn.searchengine.DocumentResults.DocumentResults (Document document, int numberOfQueryWords)
Definition at line 53 of file DocumentResults.java.
Referenced by com.utn.searchengine.DocumentResults.equals().
Member Function Documentation
boolean com.utn.searchengine.DocumentResults.equals (Object obj)
Definition at line 34 of file DocumentResults.java.
References com.utn.searchengine.DocumentResults.DocumentResults(), and com.utn.searchengine.Document.getLocation().
Document com.utn.searchengine.DocumentResults.getDocument ()
Definition at line 13 of file DocumentResults.java.
Referenced by com.utn.searchengine.DocumentResults.hashCode().
int com.utn.searchengine.DocumentResults.getNumberOfQueryWords ()
numero de la palabras de la query
Returns:
Definition at line 25 of file DocumentResults.java.
int com.utn.searchengine.DocumentResults.hashCode ()
Definition at line 49 of file DocumentResults.java.
References com.utn.searchengine.DocumentResults.getDocument(), and com.utn.searchengine.Document.getLocation().
void com.utn.searchengine.DocumentResults.setDocument (Document document)
Definition at line 17 of file DocumentResults.java.
void com.utn.searchengine.DocumentResults.setNumberOfQueryWords (int numberOfQueryWords)
Definition at line 29 of file DocumentResults.java.
Referenced by dataaccess.postgresql.PostgreSQLPostListDAO.getFilteredCandidates().
The documentation for this class was generated from the following file:
src/main/java/com/utn/searchengine/DocumentResults.java