DLC Search Engine: com.utn.searchengine.StopWordMap Class Reference
com.utn.searchengine.StopWordMap Class Reference
Static Public Member Functions
static boolean readStopWordList ()
static HashMap getStopWordMap ()
static File stopWordIdiomDocumentFinder (int selectedIdiom)
static boolean isStopWord (String word)
Detailed Description
Clase StopWordMap, es un hashMap de strings que añade stop words que no deben ser indexadas.
Definition at line 15 of file StopWordMap.java.
Member Function Documentation
static HashMap com.utn.searchengine.StopWordMap.getStopWordMap () [static]
Definition at line 67 of file StopWordMap.java.
static boolean com.utn.searchengine.StopWordMap.isStopWord (String word) [static]
Definition at line 99 of file StopWordMap.java.
Referenced by com.utn.searchengine.WordCount.retrieveWordCount().
static boolean com.utn.searchengine.StopWordMap.readStopWordList () [static]
readStopWordList sirve para leer las stopword que empleo para la busqueda para eso leo un archivo .txt del idioma de stopWord que quieda de del documento o sitio visitado
Returns:
Definition at line 39 of file StopWordMap.java.
Referenced by com.utn.searchengine.WordCount.retrieveWordCount().
static File com.utn.searchengine.StopWordMap.stopWordIdiomDocumentFinder (int selectedIdiom) [static]
En funcion del idioma en que este el documento trae El archivo de stopwordXXX.txt que necesite El documento debe reconocer que tipo de idioma es.
Parameters:
selectedIdiom el idioma deseado: 0 para ingles, 1 para español
Returns:
un File con las stop words del idioma seleccionado.
Definition at line 78 of file StopWordMap.java.
Referenced by com.utn.searchengine.WordCount.retrieveWordCount().
The documentation for this class was generated from the following file:
src/main/java/com/utn/searchengine/StopWordMap.java