DLC Search Engine: com.utn.searchengine.Word Class Reference
com.utn.searchengine.Word Class Reference
Public Member Functions
Word (String name, int totalDocumentsWhereWordAppears, int maxTF)
int getMaxTF ()
int getFrecuency ()
void setMaxTF (int maxTF)
int getNr ()
void setNr (int totalDocumentsWhereWordAppears)
String getName ()
void setName (String name)
Word (String name)
boolean equals (Object obj)
int hashCode ()
String toString ()
Detailed Description
This class represents a word and gots some extra info that can be used on the Vocabulary
Author:
altamirano,peker,liberal
Definition at line 11 of file Word.java.
Constructor & Destructor Documentation
com.utn.searchengine.Word.Word (String name, int totalDocumentsWhereWordAppears, int maxTF)
Definition at line 13 of file Word.java.
Referenced by com.utn.searchengine.Word.equals().
com.utn.searchengine.Word.Word (String name)
Definition at line 51 of file Word.java.
Member Function Documentation
boolean com.utn.searchengine.Word.equals (Object obj)
Definition at line 58 of file Word.java.
References com.utn.searchengine.Word.Word().
int com.utn.searchengine.Word.getFrecuency ()
Definition at line 24 of file Word.java.
int com.utn.searchengine.Word.getMaxTF ()
Definition at line 20 of file Word.java.
Referenced by com.utn.searchengine.Vocabulary.addDocumentWords(), dataaccess.postgresql.PostgreSQLWordDAO.saveWord(), and com.utn.searchengine.Word.toString().
String com.utn.searchengine.Word.getName ()
Definition at line 42 of file Word.java.
Referenced by com.utn.searchengine.Vocabulary.addDocumentWords(), com.utn.searchengine.Vocabulary.addWord(), dataaccess.postgresql.PostgreSQLWordDAO.deleteWord(), com.utn.searchengine.LocalWordCountManager.determinateSimilitude(), dataaccess.postgresql.PostgreSQLPostListDAO.getFilteredCandidates(), dataaccess.postgresql.PostgreSQLPostListDAO.getNrWord(), dataaccess.postgresql.PostgreSQLWordDAO.getNrWord(), com.utn.searchengine.WordCount.getTF(), dataaccess.postgresql.PostgreSQLPostListDAO.getTF(), dataaccess.postgresql.PostgreSQLWordDAO.getWord(), dataaccess.postgresql.PostgreSQLPostListDAO.grabarPostList(), dataaccess.postgresql.PostgreSQLPostListDAO.obtenerDocumentoCandidatos(), and dataaccess.postgresql.PostgreSQLWordDAO.saveWord().
int com.utn.searchengine.Word.getNr ()
Definition at line 33 of file Word.java.
Referenced by com.utn.searchengine.Vocabulary.addDocumentWords(), com.utn.searchengine.LocalWordCountManager.inverseFrecuency(), dataaccess.postgresql.PostgreSQLWordDAO.saveWord(), and com.utn.searchengine.Word.toString().
int com.utn.searchengine.Word.hashCode ()
Definition at line 73 of file Word.java.
void com.utn.searchengine.Word.setMaxTF (int maxTF)
Definition at line 28 of file Word.java.
Referenced by com.utn.searchengine.Vocabulary.addDocumentWords().
void com.utn.searchengine.Word.setName (String name)
Definition at line 46 of file Word.java.
void com.utn.searchengine.Word.setNr (int totalDocumentsWhereWordAppears)
Definition at line 37 of file Word.java.
Referenced by com.utn.searchengine.Vocabulary.addDocumentWords().
String com.utn.searchengine.Word.toString ()
Definition at line 78 of file Word.java.
References com.utn.searchengine.Word.getMaxTF(), and com.utn.searchengine.Word.getNr().
The documentation for this class was generated from the following file:
src/main/java/com/utn/searchengine/Word.java