DLC Search Engine: com.utn.searchengine.Similitude Class Reference
com.utn.searchengine.Similitude Class Reference
Public Member Functions
Similitude (Document documentA, Document documentB)
Document getDocumentA ()
void setDocumentA (Document documentA)
Document getDocumentB ()
void setDocumentB (Document documentB)
double getSimilitude ()
void setSimilitude (double similitude)
String toString ()
Similitude (Document documentA, Document documentB, double similitude)
Detailed Description
This class represents the similitude between two documents
Author:
altamirano,peker,liberal
Definition at line 12 of file Similitude.java.
Constructor & Destructor Documentation
com.utn.searchengine.Similitude.Similitude (Document documentA, Document documentB)
Definition at line 14 of file Similitude.java.
com.utn.searchengine.Similitude.Similitude (Document documentA, Document documentB, double similitude)
Definition at line 52 of file Similitude.java.
Member Function Documentation
Document com.utn.searchengine.Similitude.getDocumentA ()
Definition at line 19 of file Similitude.java.
Document com.utn.searchengine.Similitude.getDocumentB ()
Definition at line 27 of file Similitude.java.
double com.utn.searchengine.Similitude.getSimilitude ()
Definition at line 35 of file Similitude.java.
Referenced by com.utn.searchengine.LocalWordCountManager.Compare.compare().
void com.utn.searchengine.Similitude.setDocumentA (Document documentA)
Definition at line 23 of file Similitude.java.
void com.utn.searchengine.Similitude.setDocumentB (Document documentB)
Definition at line 31 of file Similitude.java.
void com.utn.searchengine.Similitude.setSimilitude (double similitude)
Definition at line 39 of file Similitude.java.
String com.utn.searchengine.Similitude.toString ()
Definition at line 44 of file Similitude.java.
References com.utn.searchengine.Document.getLocation(), and com.utn.searchengine.Document.getModule().
The documentation for this class was generated from the following file:
src/main/java/com/utn/searchengine/Similitude.java