DLC Search Engine: com.utn.searchengine.Document Class Reference
com.utn.searchengine.Document Class Reference
Public Member Functions
String getLocation ()
void setLocation (String location)
String getText ()
Document (String location, String text)
Document (String location, String text, double d)
double getModule ()
void setModule (double module)
String toString ()
int hashCode ()
boolean equals (Object obj)
int compareTo (Object o)
Detailed Description
This class represents a text source, it can be a page or a text document
Author:
altamirano,peker,liberal
Definition at line 12 of file Document.java.
Constructor & Destructor Documentation
com.utn.searchengine.Document.Document (String location, String text)
Definition at line 26 of file Document.java.
Referenced by com.utn.searchengine.Document.compareTo(), and com.utn.searchengine.Document.equals().
com.utn.searchengine.Document.Document (String location, String text, double d)
Definition at line 33 of file Document.java.
Member Function Documentation
int com.utn.searchengine.Document.compareTo (Object o)
Definition at line 84 of file Document.java.
References com.utn.searchengine.Document.Document(), and com.utn.searchengine.Document.getLocation().
boolean com.utn.searchengine.Document.equals (Object obj)
Definition at line 70 of file Document.java.
References com.utn.searchengine.Document.Document().
String com.utn.searchengine.Document.getLocation ()
Definition at line 14 of file Document.java.
Referenced by com.utn.searchengine.LocalWordCountManager.addDocument(), com.utn.searchengine.Document.compareTo(), com.utn.searchengine.DocumentResults.equals(), com.utn.searchengine.LocalWordCountManager.estimateWeight(), dataaccess.postgresql.PostgreSQLPostListDAO.getTF(), dataaccess.postgresql.PostgreSQLPostListDAO.getWordsDocument(), dataaccess.postgresql.PostgreSQLPostListDAO.grabarPostList(), dataaccess.postgresql.PostgreSQLDocumentDAO.grabarWebSite(), com.utn.searchengine.DocumentResults.hashCode(), dataaccess.postgresql.PostgreSQLDocumentDAO.obtenerDocument(), and com.utn.searchengine.Similitude.toString().
double com.utn.searchengine.Document.getModule ()
Definition at line 45 of file Document.java.
Referenced by com.utn.searchengine.LocalWordCountManager.estimateWeight(), com.utn.searchengine.DocumentManager.getDocumentModule(), dataaccess.postgresql.PostgreSQLDocumentDAO.grabarWebSite(), and com.utn.searchengine.Similitude.toString().
String com.utn.searchengine.Document.getText ()
Definition at line 22 of file Document.java.
Referenced by com.utn.searchengine.WordCount.getTF(), and com.utn.searchengine.WordCount.retrieveWordCount().
int com.utn.searchengine.Document.hashCode ()
Definition at line 63 of file Document.java.
void com.utn.searchengine.Document.setLocation (String location)
Definition at line 18 of file Document.java.
void com.utn.searchengine.Document.setModule (double module)
Definition at line 50 of file Document.java.
Referenced by com.utn.searchengine.LocalWordCountManager.determinateBestSimilitude(), com.utn.searchengine.LocalWordCountManager.estimateWeight(), and dataaccess.postgresql.PostgreSQLDocumentDAO.obtenerDocument().
String com.utn.searchengine.Document.toString ()
Definition at line 57 of file Document.java.
The documentation for this class was generated from the following file:
src/main/java/com/utn/searchengine/Document.java