DLC Search Engine: dataaccess.postgresql.PostgreSQLDocumentDAO Class Reference
dataaccess.postgresql.PostgreSQLDocumentDAO Class Reference
Public Member Functions
boolean grabarWebSite (Document document)
int obtenerCantidadDocument ()
Document obtenerDocument (Document website)
Detailed Description
Author:
Altamirano Peker Liberal
Definition at line 15 of file PostgreSQLDocumentDAO.java.
Member Function Documentation
boolean dataaccess.postgresql.PostgreSQLDocumentDAO.grabarWebSite (Document document)
Graba el Document en la base de datos. Si no existia la inserta y si existia la actualiza
Parameters:
document Document a grabar
Returns:
true si se pudo grabar con éxito, false en caso contrario
Implements dataaccess.dao.DocumentDAO.
Definition at line 23 of file PostgreSQLDocumentDAO.java.
References dataaccess.dbmanager.PostgreDBManager.getConnection(), com.utn.searchengine.Document.getLocation(), and com.utn.searchengine.Document.getModule().
int dataaccess.postgresql.PostgreSQLDocumentDAO.obtenerCantidadDocument ()
Obtiene la cantidad de documentos
Returns:
la cantidad de documentos
Implements dataaccess.dao.DocumentDAO.
Definition at line 46 of file PostgreSQLDocumentDAO.java.
References dataaccess.dbmanager.PostgreDBManager.getConnection().
Document dataaccess.postgresql.PostgreSQLDocumentDAO.obtenerDocument (Document website)
Obtiene el Document desde la base de datos que se corresponde a la Document de busqueda dada.
Parameters:
document Document que se desea buscar en la base de datos
Returns:
el Document de de la base de datos, null en caso que no exista o se produzca algun error.
Implements dataaccess.dao.DocumentDAO.
Definition at line 77 of file PostgreSQLDocumentDAO.java.
References dataaccess.dbmanager.PostgreDBManager.getConnection(), com.utn.searchengine.Document.getLocation(), and com.utn.searchengine.Document.setModule().
The documentation for this class was generated from the following file:
src/main/java/DataAccess/postgresql/PostgreSQLDocumentDAO.java