DLC Search Engine: dataaccess.dao.DocumentDAO Interface Reference
dataaccess.dao.DocumentDAO Interface Reference
Public Member Functions
boolean grabarWebSite (Document document)
int obtenerCantidadDocument ()
Document obtenerDocument (Document website)
Detailed Description
Esta interface define las operaciones validas a realizarse en términos de persistencia sobre un objeto de tipo Document.
Author:
Altamirado Liberal Peker
Definition at line 11 of file DocumentDAO.java.
Member Function Documentation
boolean dataaccess.dao.DocumentDAO.grabarWebSite (Document document)
Graba un Document en la base de datos. Si la Document ya existia la actualiza y si no existia la inserta en la base de datos.
Parameters:
Document la Document a grabar
Returns:
true si la operacion se pudo realizar exitosamente, false en caso contrario
Implemented in dataaccess.postgresql.PostgreSQLDocumentDAO.
Referenced by com.utn.searchengine.DocumentManager.addDocument(), and com.utn.searchengine.DocumentManager.setDocumentModule().
int dataaccess.dao.DocumentDAO.obtenerCantidadDocument ()
Obtiene la cantidad de documentos
Returns:
la cantidad de documentos
Implemented in dataaccess.postgresql.PostgreSQLDocumentDAO.
Referenced by com.utn.searchengine.DocumentManager.DocumentManager().
Document dataaccess.dao.DocumentDAO.obtenerDocument (Document website)
Parameters:
website
Returns:
El documento correspondiente
Implemented in dataaccess.postgresql.PostgreSQLDocumentDAO.
Referenced by com.utn.searchengine.DocumentManager.getDocumentModule().
The documentation for this interface was generated from the following file:
src/main/java/DataAccess/dao/DocumentDAO.java