JSpider Library: com.spider.jspiderlibrary2.Communicator Class Reference
com.spider.jspiderlibrary2.Communicator Class Reference
Public Member Functions
void run ()
void initSpider ()
boolean spiderFoundURL (URL base, URL url)
void spiderFoundURLError (URL url)
Static Public Member Functions
static ArrayList SearchEngineContentToUi (ArrayList< String > listOfLinks)
Static Public Attributes
static String textToCrawl
static boolean crawl = false
static boolean search = false
static HashMap pages
static int totalLinks
static ArrayList linksprocessed = new ArrayList()
static ArrayList linkserror = new ArrayList()
Protected Member Functions
boolean checkLink (URL url)
Protected Attributes
Spider spider
URL base
int badLinksCount = 0
int goodLinksCount = 0
Detailed Description
Author:
altamirano,peker,liberal
Definition at line 14 of file Communicator.java.
Member Function Documentation
boolean com.spider.jspiderlibrary2.Communicator.checkLink (URL url) [protected]
Definition at line 94 of file Communicator.java.
Referenced by com.spider.jspiderlibrary2.Communicator.spiderFoundURL().
void com.spider.jspiderlibrary2.Communicator.initSpider ()
Definition at line 54 of file Communicator.java.
References com.spider.jspiderlibrary2.Spider.addURL(), com.spider.jspiderlibrary2.Communicator.base, com.spider.jspiderlibrary2.Spider.begin(), com.spider.jspiderlibrary2.Spider.clear(), com.spider.jspiderlibrary2.Communicator.spider, and com.spider.jspiderlibrary2.Communicator.textToCrawl.
Referenced by com.spider.jspiderlibrary2.Communicator.run().
void com.spider.jspiderlibrary2.Communicator.run ()
Definition at line 34 of file Communicator.java.
References com.spider.jspiderlibrary2.Communicator.crawl, com.spider.jspiderlibrary2.Communicator.initSpider(), com.spider.jspiderlibrary2.Communicator.linkserror, com.spider.jspiderlibrary2.Communicator.linksprocessed, com.spider.jspiderlibrary2.Communicator.pages, com.spider.jspiderlibrary2.Communicator.spider, com.spider.jspiderlibrary2.Communicator.totalLinks, com.spider.jspiderlibrary2.Spider.workloadError, and com.spider.jspiderlibrary2.Spider.workloadProcessed.
static ArrayList com.spider.jspiderlibrary2.Communicator.SearchEngineContentToUi (ArrayList< String > listOfLinks) [static]
Definition at line 113 of file Communicator.java.
boolean com.spider.jspiderlibrary2.Communicator.spiderFoundURL (URL base, URL url)
Implements com.spider.jspiderlibrary2.ISpiderReportable.
Definition at line 75 of file Communicator.java.
References com.spider.jspiderlibrary2.Communicator.badLinksCount, com.spider.jspiderlibrary2.Communicator.checkLink(), and com.spider.jspiderlibrary2.Communicator.goodLinksCount.
void com.spider.jspiderlibrary2.Communicator.spiderFoundURLError (URL url)
Implements com.spider.jspiderlibrary2.ISpiderReportable.
Definition at line 109 of file Communicator.java.
References com.spider.jspiderlibrary2.Communicator.badLinksCount.
Member Data Documentation
int com.spider.jspiderlibrary2.Communicator.badLinksCount = 0 [protected]
Definition at line 23 of file Communicator.java.
Referenced by com.spider.jspiderlibrary2.Communicator.spiderFoundURL(), and com.spider.jspiderlibrary2.Communicator.spiderFoundURLError().
URL com.spider.jspiderlibrary2.Communicator.base [protected]
Definition at line 22 of file Communicator.java.
Referenced by com.spider.jspiderlibrary2.Communicator.initSpider().
boolean com.spider.jspiderlibrary2.Communicator.crawl = false [static]
Definition at line 19 of file Communicator.java.
Referenced by com.spider.jspiderlibrary2.Communicator.run().
int com.spider.jspiderlibrary2.Communicator.goodLinksCount = 0 [protected]
Definition at line 24 of file Communicator.java.
Referenced by com.spider.jspiderlibrary2.Communicator.spiderFoundURL().
ArrayList com.spider.jspiderlibrary2.Communicator.linkserror = new ArrayList() [static]
Definition at line 28 of file Communicator.java.
Referenced by com.spider.jspiderlibrary2.Communicator.run().
ArrayList com.spider.jspiderlibrary2.Communicator.linksprocessed = new ArrayList() [static]
Definition at line 27 of file Communicator.java.
Referenced by com.spider.jspiderlibrary2.Communicator.run().
HashMap com.spider.jspiderlibrary2.Communicator.pages [static]
Definition at line 25 of file Communicator.java.
Referenced by com.spider.jspiderlibrary2.Communicator.run().
boolean com.spider.jspiderlibrary2.Communicator.search = false [static]
Definition at line 20 of file Communicator.java.
Spider com.spider.jspiderlibrary2.Communicator.spider [protected]
Definition at line 21 of file Communicator.java.
Referenced by com.spider.jspiderlibrary2.Communicator.initSpider(), and com.spider.jspiderlibrary2.Communicator.run().
String com.spider.jspiderlibrary2.Communicator.textToCrawl [static]
Definition at line 17 of file Communicator.java.
Referenced by com.spider.jspiderlibrary2.Communicator.initSpider().
int com.spider.jspiderlibrary2.Communicator.totalLinks [static]
Definition at line 26 of file Communicator.java.
Referenced by com.spider.jspiderlibrary2.Spider.processURL(), and com.spider.jspiderlibrary2.Communicator.run().
The documentation for this class was generated from the following file:
src/main/java/com/spider/jspiderlibrary2/Communicator.java