JSpider Library: com.spider.jspiderlibrary2.Spider Class Reference
com.spider.jspiderlibrary2.Spider Class Reference
Classes
class Parser
Public Member Functions
Spider (ISpiderReportable report)
Collection getWorkloadError ()
Collection getWorkloadWaiting ()
Collection getWorkloadProcessed ()
void clear ()
void cancel ()
void addURL (URL url)
void processURL (URL url)
HashMap getHashMapPages ()
void clearHashMapPages ()
void begin ()
void log (String entry)
Protected Attributes
ArrayList workloadError = new ArrayList(3)
ArrayList workloadWaiting = new ArrayList(3)
ArrayList workloadProcessed = new ArrayList(3)
ISpiderReportable report
boolean cancel = false
Detailed Description
Author:
altamirano,peker,liberal
Clase spider empleada para crawlear todo el sitio web, a travez de una url base sin salir de corriente dominio, y con la capacidad de retornar, el texto html leido de cada url del sitio que se encuentra dentro de la base
Definition at line 20 of file Spider.java.
Constructor & Destructor Documentation
com.spider.jspiderlibrary2.Spider.Spider (ISpiderReportable report)
Parameters:
report Es para aquella clase que implemente la interface ISpiderReportable, y dicha clase va a recibir la informacion que el spider encuentre
Definition at line 70 of file Spider.java.
References com.spider.jspiderlibrary2.Spider.report.
Member Function Documentation
void com.spider.jspiderlibrary2.Spider.addURL (URL url)
Añado una URL a procesar.
Parameters:
url
Definition at line 122 of file Spider.java.
References com.spider.jspiderlibrary2.Spider.getWorkloadError(), com.spider.jspiderlibrary2.Spider.getWorkloadProcessed(), com.spider.jspiderlibrary2.Spider.getWorkloadWaiting(), and com.spider.jspiderlibrary2.Spider.log().
Referenced by com.spider.jspiderlibrary2.Spider.Parser.handleLink(), and com.spider.jspiderlibrary2.Communicator.initSpider().
void com.spider.jspiderlibrary2.Spider.begin ()
Metodo que lanza el spider
Definition at line 234 of file Spider.java.
References com.spider.jspiderlibrary2.Spider.cancel(), com.spider.jspiderlibrary2.Spider.getWorkloadProcessed(), com.spider.jspiderlibrary2.Spider.getWorkloadWaiting(), and com.spider.jspiderlibrary2.Spider.processURL().
Referenced by com.spider.jspiderlibrary2.Communicator.initSpider().
void com.spider.jspiderlibrary2.Spider.cancel ()
Setea la flag que genera que el metodo begin retorne al ser terminado.
Definition at line 113 of file Spider.java.
Referenced by com.spider.jspiderlibrary2.Spider.begin().
void com.spider.jspiderlibrary2.Spider.clear ()
Borra todas las colecciones.
Definition at line 102 of file Spider.java.
References com.spider.jspiderlibrary2.Spider.clearHashMapPages(), com.spider.jspiderlibrary2.Spider.getWorkloadError(), com.spider.jspiderlibrary2.Spider.getWorkloadProcessed(), and com.spider.jspiderlibrary2.Spider.getWorkloadWaiting().
Referenced by com.spider.jspiderlibrary2.Communicator.initSpider().
void com.spider.jspiderlibrary2.Spider.clearHashMapPages ()
Definition at line 227 of file Spider.java.
Referenced by com.spider.jspiderlibrary2.Spider.clear().
HashMap com.spider.jspiderlibrary2.Spider.getHashMapPages ()
Definition at line 222 of file Spider.java.
Collection com.spider.jspiderlibrary2.Spider.getWorkloadError ()
Trae la coleccion de URL con errores.
Returns:
una colleccion de URLs.
Definition at line 79 of file Spider.java.
References com.spider.jspiderlibrary2.Spider.workloadError.
Referenced by com.spider.jspiderlibrary2.Spider.addURL(), com.spider.jspiderlibrary2.Spider.clear(), and com.spider.jspiderlibrary2.Spider.processURL().
Collection com.spider.jspiderlibrary2.Spider.getWorkloadProcessed ()
Traen las URLS que estan ya procesadas
Returns:
una colleccion de URLs.
Definition at line 95 of file Spider.java.
References com.spider.jspiderlibrary2.Spider.workloadProcessed.
Referenced by com.spider.jspiderlibrary2.Spider.addURL(), com.spider.jspiderlibrary2.Spider.begin(), com.spider.jspiderlibrary2.Spider.clear(), and com.spider.jspiderlibrary2.Spider.processURL().
Collection com.spider.jspiderlibrary2.Spider.getWorkloadWaiting ()
Traen las URLS que estan esperando a ser procesadas
Returns:
una colleccion de URLs.
Definition at line 87 of file Spider.java.
References com.spider.jspiderlibrary2.Spider.workloadWaiting.
Referenced by com.spider.jspiderlibrary2.Spider.addURL(), com.spider.jspiderlibrary2.Spider.begin(), com.spider.jspiderlibrary2.Spider.clear(), and com.spider.jspiderlibrary2.Spider.processURL().
void com.spider.jspiderlibrary2.Spider.log (String entry)
Called internally to log information This basic method just writes the log out to the stdout. Emplea un log para controlar lo que va realizando el parser
Parameters:
entry The information to be written to the log.
Definition at line 419 of file Spider.java.
Referenced by com.spider.jspiderlibrary2.Spider.addURL(), and com.spider.jspiderlibrary2.Spider.Parser.handleLink().
void com.spider.jspiderlibrary2.Spider.processURL (URL url)
Procesa una URL
Parameters:
url la url que va a ser procesada
Definition at line 178 of file Spider.java.
References com.spider.jspiderlibrary2.HTMLParse.getParser(), com.spider.jspiderlibrary2.Spider.getWorkloadError(), com.spider.jspiderlibrary2.Spider.getWorkloadProcessed(), com.spider.jspiderlibrary2.Spider.getWorkloadWaiting(), com.spider.jspiderlibrary2.Spider.report, com.spider.jspiderlibrary2.RobotsParser.robotSafe(), com.spider.jspiderlibrary2.ISpiderReportable.spiderFoundURLError(), and com.spider.jspiderlibrary2.Communicator.totalLinks.
Referenced by com.spider.jspiderlibrary2.Spider.begin().
Member Data Documentation
boolean com.spider.jspiderlibrary2.Spider.cancel = false [protected]
Flags que indican cuando el proceso del crawler debe ser cancelado
Definition at line 60 of file Spider.java.
ISpiderReportable com.spider.jspiderlibrary2.Spider.report [protected]
Un hash map que añade URL que estan ya procesadas con su texto La key es la url y el value es el string builder con todo el texto Una Coleccion de URLs que no seran usadas porque no emplean texto significativo
Definition at line 55 of file Spider.java.
Referenced by com.spider.jspiderlibrary2.Spider.Parser.handleLink(), com.spider.jspiderlibrary2.Spider.processURL(), and com.spider.jspiderlibrary2.Spider.Spider().
ArrayList com.spider.jspiderlibrary2.Spider.workloadError = new ArrayList(3) [protected]
Una Coleccion de URLs que resultan erroneas
Definition at line 29 of file Spider.java.
Referenced by com.spider.jspiderlibrary2.Spider.getWorkloadError(), and com.spider.jspiderlibrary2.Communicator.run().
ArrayList com.spider.jspiderlibrary2.Spider.workloadProcessed = new ArrayList(3) [protected]
Definition at line 35 of file Spider.java.
Referenced by com.spider.jspiderlibrary2.Spider.getWorkloadProcessed(), and com.spider.jspiderlibrary2.Communicator.run().
ArrayList com.spider.jspiderlibrary2.Spider.workloadWaiting = new ArrayList(3) [protected]
Una Coleccion de URLs que estan esperando para ser procesadas Cada URL añadida sirve para iniciar el crawleo del sitio
Definition at line 34 of file Spider.java.
Referenced by com.spider.jspiderlibrary2.Spider.getWorkloadWaiting().
The documentation for this class was generated from the following file:
src/main/java/com/spider/jspiderlibrary2/Spider.java